name: Notice Crawler

on:
  schedule:
    - cron: '0 * * * *' # 매시간 0분에 자동 실행 (UTC 기준)
  workflow_dispatch: # 수동 실행 버튼 활성화

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # 최신 라이브러리 지원을 위해 3.11 사용

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable # 셀레니엄 실행을 위한 브라우저 설치

      - name: Debug file structure
        run: |
          pwd
          ls -R
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ai_server/requirements.txt

      - name: Run Crawler & AI
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }} # 깃허브 Secrets에 저장된 JSON 키
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python ai_server/crawler.py

      - name: Run Cafeteria Scraper
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: python ai_server/cafeteria_scraper.py
